_target_: src.utils.VllmEmbedding
model_path: ${connected_dir}/models
model_base: Qwen3-Embedding-0.6B
model_ft_data: base
model_default_upload_user: Qwen
num_gpus: ${devices}
seed: ${seed}
gpu_memory_utilization: ${reward.embedding_gpu_memory_utilization}
max_length: ${max_new_tokens}
instruction_length: 32
instruction: |
  Given a query, retrieve relevant passages that answer the query.
device_id: null
master_addr: 127.0.0.1
master_port: 29501
nccl_socket_ifname: lo
nccl_ib_disable: 1