_target_: src.utils.RewardManager
rewards:
  - _target_: src.utils.ThinkFormatReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.think_format}
    is_enable_thinking: ${is_enable_thinking}

  - _target_: src.utils.AnswerFormatReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.answer_format}

  - _target_: src.utils.MatchReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.match}

  - _target_: src.utils.CodeExecutionReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.code_execution}
    timeout: ${reward.timeout}

  - _target_: src.utils.RougeReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.rouge}
    rouge_type: ${reward.rouge_type}

  - _target_: src.utils.EquationReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.equation}
    equation_target_column_name: ${reward.equation_target_column_name}
    equation_numbers_column_name: ${reward.equation_numbers_column_name}

  - _target_: src.utils.RetrievalHitReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.retrieval_hit}
    database: ${reward_database}
    embedding: ${reward_embedding}
    margin: ${reward.retrieval_margin}
    tau: ${reward.retrieval_tau}

  - _target_: src.utils.SingleKVReward
    is_answer_tag: ${reward.is_answer_tag}
    think_start_token: ${reward.think_start_token}
    think_end_token: ${reward.think_end_token}
    answer_start_token: ${reward.answer_start_token}
    answer_end_token: ${reward.answer_end_token}
    eos_token: ${reward.eos_token}
    weight: ${reward.weight.vlm_single_kv}
    json_parse_weight: ${reward.json_parse_weight}