structural:
  _target_: src.datasets.DPOStructuralDataset
  data_path: ${connected_dir}/data
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  data_column_name: ${data_column_name}
  chosen_column_name: ${chosen_column_name}
  rejected_column_name: ${rejected_column_name}
  role_column_name: ${role_column_name}
  content_column_name: ${content_column_name}
  assistant_column_name: ${assistant_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}

conversational:
  _target_: src.datasets.DPOConversationalDataset
  data_path: ${connected_dir}/data
  split_ratio: ${split_ratio}
  is_strict_split: ${is_strict_split}
  seed: ${seed}
  dataset_name: ${dataset_name}
  dataset_format: ${dataset_format}
  prompt_column_name: ${prompt_column_name}
  chosen_column_name: ${chosen_column_name}
  rejected_column_name: ${rejected_column_name}
  modality: ${modality}
  max_pixels: ${max_pixels}
  do_resize: ${do_resize}